server:
  port: 8080
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/users
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: root123456
 thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  check-template-location: true
  encoding: UTF-8
  mode: HTML5
  cache: false 
  servlet:
   content-type: text/html
 resources: 
  static-locations: classpath:/static/
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.cheung.mybatis.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 
    

